# 텐서 연산

```py
keras.layers.Dense(512, activation='relu')
output = relu(dot(W, input) + b)
```
W = 2D 텐서  
b = 벡터

## 원소별 연산
relu 함수와 덧셈이 속함

In [4]:
def naive_relu(x):
    assert len(x.shape)
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [6]:
def naive_add(x, y):
    assert len(x.shape)
    assert x.shape == y.shape
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [16]:
import numpy as np
aa = np.array([[-1,2],[2, 3]])
bb = np.array([[2,3],[3, 4]])
print(naive_relu(aa))
print(naive_add(aa,bb))

z = aa + bb
print(z)

np.maximum(z, 0.)

[[0 2]
 [2 3]]
[[1 5]
 [5 7]]
[[1 5]
 [5 7]]


array([[1., 5.],
       [5., 7.]])

## 브로드캐스팅
연산을 위해 크기가 작은 텐서가 큰 텐서의 크기에 맞추는 것
1. 큰텐서의 ndim에 맞도록 작은 텐서에 축이 추가됨
2. 작은 텐서가 새 축을 따라서 큰 텐서의 크기에 맞도록 반복

ex) x = (32, 10), y = (10,)일 때 y의 비어있는 축을 추가하여(1,10) 32번 반복시 연산할 수 있게됨

In [17]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [28]:
import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))

In [31]:
z = np.maximum(x, y)

## 텐서 점곱

### 벡터 * 벡터

In [33]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [35]:
naive_vector_dot(np.array([1,2,3]), np.array([4,5,6]))

32.0

### 행렬 * 벡터

In [36]:
import numpy as np
def naive_metrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[i]
    return z

### 행렬 * 행렬

In [37]:
def naive_metrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            row_x = x[i,:]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

(a, b, c, d) * (d,) -> (a, b, c)  
(a, b, c, d) * (d, e) -> (a, b, c, e)

## 텐서 크기 변환

In [39]:
x = np.array([[0., 1.],
            [2., 3.],
            [4., 5.]])

In [40]:
print(x.shape)

(3, 2)


In [50]:
x = x.reshape((6,1))

In [51]:
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [52]:
x = x.reshape((2,3))

In [53]:
x

array([[0., 1., 2.],
       [3., 4., 5.]])

### 전치(transposition)
행과 열을 바꿈

In [55]:
x = np.zeros((300, 20))
x = np.transpose(x)
print(x.shape)

(20, 300)
